### ISSUE TITLE
jupyter readme versus text readme

### ISSUE THREAD

**Issue by adamjonas** [learn-co-curriculum/python-lists-readme#2]
It feels a little weird to have this as a jupyter readme given there is no interaction solicited. I kept looking for places to solve things, but the content didn't necessarily need to be interactive. Nothing all the "wrong," just wondering about the need for this given jupyter readmes feel like a degraded readme experience compared to native readmes.

**Comment by JeffKatzy** [comment]
@adamjonas yea - that's interesting to think about...about whether we should take more advantage of the interactivity in Jupyter during readmes, and if not, it's better just to have markdown.
