### ISSUE TITLE
New SSH Keys?

### ISSUE THREAD

**Issue by liamkillion** [learn-co-curriculum/python-lists-readme#3]
I seem to get a new SSH key every 15 minutes.  Is that normal?
<img width="1065" alt="screen shot 2018-04-03 at 6 30 10 pm" src="https://user-images.githubusercontent.com/22900398/38279185-1baec226-376d-11e8-90de-0fa340c4ef43.png">

**Comment by talum** [comment]
This is fixed now.

**Comment by liamkillion** [comment]
@talum Thanks!
